# Generated by Django 5.2.9 on 2026-04-10 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_image_url', models.URLField(max_length=500)),
                ('match_found', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('compreface_response', models.JSONField(blank=True, help_text='Raw API response', null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identifications_performed', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_logs', to='subjects.subject')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['officer', 'timestamp'], name='identificat_officer_441126_idx'), models.Index(fields=['subject', 'timestamp'], name='identificat_subject_19232f_idx'), models.Index(fields=['match_found'], name='identificat_match_f_f1cb0b_idx')],
            },
        ),
    ]
