# Generated by Django 5.2.9 on 2026-04-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identificationlog',
            old_name='compreface_response',
            new_name='face_recognition_response',
        ),
    ]
