# Generated by Django 5.2.9 on 2026-04-10 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offence_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('offence_category', models.CharField(choices=[('THEFT', 'Theft'), ('ASSAULT', 'Assault / Battery'), ('ARMED_ROBBERY', 'Armed Robbery'), ('FRAUD', 'Fraud / Scam'), ('HOMICIDE', 'Homicide / Murder'), ('KIDNAPPING', 'Kidnapping'), ('EXTORTION', 'Extortion'), ('DRUGS', 'Drug Trafficking / Possession'), ('CYBERCRIME', 'Cybercrime'), ('TRAFFIC', 'Traffic Violation'), ('OTHER', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SERIOUS', 'Serious'), ('VIOLENT', 'Violent'), ('CAPITAL', 'Capital Offence')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('ACQUITTED', 'Acquitted'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('offence_title', models.CharField(help_text="Short descriptor, e.g. 'Robbery at gunpoint'", max_length=200)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField(help_text='When the offence occurred')),
                ('reported_date', models.DateTimeField(auto_now_add=True, help_text='When logged in system')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('evidence_images', models.JSONField(blank=True, default=list, help_text='List of Cloudinary URLs')),
                ('court_case_number', models.CharField(blank=True, max_length=100, null=True)),
                ('penalty_issued', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arresting_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrests_made', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offences_handled', to='authentication.policestation')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offences', to='subjects.subject')),
            ],
            options={
                'ordering': ['-incident_date'],
                'indexes': [models.Index(fields=['offence_code'], name='offences_of_offence_58c2bd_idx'), models.Index(fields=['subject', 'status'], name='offences_of_subject_fa513c_idx'), models.Index(fields=['offence_category'], name='offences_of_offence_9ced0e_idx')],
            },
        ),
    ]
