# Generated by Django 5.2.9 on 2026-04-10 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_number', models.CharField(db_index=True, help_text='e.g. LSP-04821', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('rank', models.CharField(help_text='e.g. Inspector, Sergeant', max_length=100)),
                ('role', models.CharField(choices=[('FIELD_OFFICER', 'Field Officer'), ('SUPERVISOR', 'Supervisor'), ('ANALYST', 'Analyst'), ('ADMIN', 'Administrator')], default='FIELD_OFFICER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['badge_number'],
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('division', models.CharField(blank=True, max_length=200)),
                ('lga', models.CharField(max_length=100, verbose_name='LGA')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commanding_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Stations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='officer',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='authentication.policestation'),
        ),
    ]
