# Generated by Django 5.2.9 on 2026-04-10 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='e.g. SUBJECT_VIEWED, SUBJECT_CREATED, OFFENCE_CREATED, OFFENCE_UPDATED, IDENTIFICATION_ATTEMPTED, WANTED_ADDED, OFFICER_CREATED, OFFICER_UPDATED', max_length=100)),
                ('target_type', models.CharField(blank=True, help_text='Model name, e.g. Subject, Offence, WantedPerson', max_length=100)),
                ('target_id', models.UUIDField(blank=True, help_text='PK of the affected record', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contextual data at time of action (diffs, scores, locations)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
