# Generated by Django 5.2.9 on 2026-04-10 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of known a.k.a.')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=20)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('lga_of_origin', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone_numbers', models.JSONField(blank=True, default=list)),
                ('identifying_marks', models.TextField(blank=True, help_text='Scars, tattoos, clear features')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('EXTREME', 'Extreme Risk')], default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active on Streets'), ('WANTED', 'Wanted'), ('INCARCERATED', 'Incarcerated'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=20)),
                ('is_armed_dangerous', models.BooleanField(default=False)),
                ('compreface_subject_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='subjects_su_last_na_5007cf_idx'), models.Index(fields=['compreface_subject_id'], name='subjects_su_compref_81d208_idx'), models.Index(fields=['status'], name='subjects_su_status_c06407_idx'), models.Index(fields=['risk_level'], name='subjects_su_risk_le_c366a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mugshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('capture_date', models.DateTimeField(auto_now_add=True)),
                ('enrolled_in_compreface', models.BooleanField(default=False)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mugshots', to='subjects.subject')),
            ],
            options={
                'ordering': ['-capture_date'],
            },
        ),
    ]
