# Generated by Django 5.2.9 on 2026-04-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='last_known_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='last_known_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='last_known_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='last_seen_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
