# Generated by Django 5.2.9 on 2026-04-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_last_known_lat_subject_last_known_lng_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subject',
            name='subjects_su_compref_81d208_idx',
        ),
        migrations.RenameField(
            model_name='mugshot',
            old_name='enrolled_in_compreface',
            new_name='enrolled_in_face_recognition',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='compreface_subject_id',
            new_name='face_recognition_id',
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['face_recognition_id'], name='subjects_su_face_re_4eae33_idx'),
        ),
    ]
