# Generated by Django 5.2.9 on 2026-04-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_subjects_su_compref_81d208_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mugshot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mugshot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
