# Generated by Django 5.2.9 on 2026-04-10 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warrant_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('issuing_authority', models.CharField(help_text='e.g. Lagos State High Court', max_length=200)),
                ('reason', models.TextField(help_text='Detailed reason for the warrant')),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical (Armed & Dangerous)')], default='ROUTINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warrants_issued', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warrants', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Wanted Person',
                'verbose_name_plural': 'Wanted Persons',
                'ordering': ['-priority', '-issued_date'],
            },
        ),
    ]
